version: '2'
services:
  nextcloud:
    build: .
    container_name: nextcloud
    links:
      - nextcloud-mariadb
      - nextcloud-redis
    depends_on:
      - onlyoffice-documentserver
    restart: always
    networks:
      - nextcloud
      - onlyoffice
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/data:/var/www/html/data
      - ./nextcloud/config:/var/www/html/config
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nextcloud-mariadb:
    container_name: nextcloud-mariadb
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty78
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=qwerty67
    restart: always
    networks:
      - nextcloud
    volumes:
      - ./nextcloud/db:/var/lib/mysql

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis
    restart: always
    networks:
      - nextcloud
    expose:
      - '6379'

  onlyoffice-documentserver-data:
    container_name: onlyoffice-documentserver-data
    image: onlyoffice/documentserver:latest
    environment:
      - ONLYOFFICE_DATA_CONTAINER=true
      - POSTGRESQL_SERVER_HOST=onlyoffice-postgresql
      - POSTGRESQL_SERVER_PORT=5432
      - POSTGRESQL_SERVER_DB_NAME=onlyoffice
      - POSTGRESQL_SERVER_USER=onlyoffice
      - RABBITMQ_SERVER_URL=amqp://guest:guest@onlyoffice-rabbitmq
      - REDIS_SERVER_HOST=onlyoffice-redis
      - REDIS_SERVER_PORT=6379
    stdin_open: true
    restart: always
    networks:
      - onlyoffice
    volumes:
       - ./onlyoffice/data:/var/www/onlyoffice/Data
       - ./onlyoffice/log:/var/log/onlyoffice
       
  onlyoffice-documentserver:
    container_name: onlyoffice-documentserver
    image: onlyoffice/documentserver:latest
    depends_on:
      - onlyoffice-documentserver-data
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    environment:
      - ONLYOFFICE_DATA_CONTAINER_HOST=onlyoffice-documentserver-data
      - BALANCE=uri depth 3
      - EXCLUDE_PORTS=443
      - HTTP_CHECK=GET /healthcheck
      - EXTRA_SETTINGS=http-check expect string true
    stdin_open: true
    restart: always
    networks:
      - onlyoffice
      - nextcloud
    ports:
      - '81:80'
      - '444:443'
    volumes_from:
     - onlyoffice-documentserver-data
     
  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    networks:
     - onlyoffice
    expose:
      - '6379'

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    networks:
     - onlyoffice
    expose:
      - '5672'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
    networks:
      - onlyoffice
    restart: always
    expose:
      - '5432'
    volumes:
      - .onlyoffice/db:/var/lib/postgresql

networks:
  nextcloud:
    driver: 'bridge'
  onlyoffice:
    driver: 'bridge'
